#ifndef LAB1LLP_COLUMN_TYPES_H
#define LAB1LLP_COLUMN_TYPES_H

enum CellType {
    TABLE_TYPE_BOOL = 0,
    TABLE_TYPE_INT = 1,
    TABLE_TYPE_VARCHAR = 2,
    TABLE_TYPE_BIGINT = 3,
    TABLE_TYPE_EMPTY = 4,
    TABLE_TYPE_FLOAT = 5
};

#endif //LAB1LLP_COLUMN_TYPES_H
